name: Deploy to Netlify on commits to master
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2

    #   - name: Setup Hugo
    #     uses: peaceiris/actions-hugo@v2
    #     with:
    #       hugo-version: '0.85.0'
    #       # extended: true

      - name:  Copy the right static files
        run: |
            mkdir ./output/
            mkdir ./output/assets
            cp -r ./assets/* ./output/assets/
            cp -r index.html ./output/index.html
            cp -r styles.css ./output/styles.css
            cp -r robots.txt ./output/robots.txt

      # Deploy the site with netlify-cli
      # - name: Deploy Site
      #   env:
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #   run: netlify deploy --dir ./output/ --prod